### PR TITLE
Create Q1

### PR DESCRIPTION
**Pull request by TanayShukla**

### CODE REVIEW

**Comment by ritviksharma3** [comment]
@TanayShukla You have not added the screenshot to Q1. Kindly add that and resubmit request.

**Review by ritviksharma3 — CHANGES_REQUESTED** [review]
@TanayShukla You have not added the screenshot to Q1. Kindly add that ASAP.

**Comment by TanayShukla** [comment]
App ye aprove to karo mai sare dal raha hu

**Comment by ritviksharma3** [comment]
@TanayShukla Sorry, We won't be able to accept the PR until it matches with our requirement.

**Pull request closed without merging**
